# Generated by Django 3.2.15 on 2022-11-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermember',
            name='received',
            field=models.BooleanField(default=False),
        ),
    ]
