# Generated by Django 3.2.16 on 2022-12-06 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0002_registermember_received'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registermember',
            name='invite_code',
        ),
        migrations.AddField(
            model_name='registermember',
            name='inviter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
